name: Task CI

on:
  pull_request:
    paths:
      - .github/workflows/task.yml
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: ./gradlew build
